[package]
name = "iron-cms"
version = "0.2.1"
authors = ["Evgeny Ukhanov <mrlsd@ya.ru>"]

[dependencies]
iron = "0.4.0"
router = "0.4.0"
handlebars-iron = "0.19.1"
rustc-serialize = "*"
time = "*"
staticfile = "*"
mount = "*"