[package]
name = "iron-cms"
version = "0.2.6"
authors = ["Evgeny Ukhanov <mrlsd@ya.ru>"]

[dependencies]
iron = "0.4.0"
router = "*"
handlebars-iron = "*"
rustc-serialize = "*"
time = "*"
staticfile = "*"
mount = "*"
maplit = "*"
handlebars = "*"

[features]
